version: "3.9"
services:
  frontend:
    build:
      context: ./front
    container_name: goaway-frontend
    ports:
      - "4200:80"
    depends_on:
      - backend

  db:
    image: mysql:8.0
    container_name: goaway-db
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - db_data:/var/lib/mysql

  backend:
    build:
      context: ./back
    container_name: goaway-backend
    ports:
      - "8080:8080" # Puerto de la aplicación
      - "5005:5005" # Puerto del depurador
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/goaway
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      SPRING_JPA_HIBERNATE_DDL_AUTO: update

volumes:
  db_data:
